# Need ceph-external-cluster-details-exporter.py from your stable OCS operator
# to genrate the external_cluster_details
---
kind: Secret
apiVersion: v1
metadata:
  name: rook-ceph-external-cluster-details
  namespace: openshift-storage
data:
  external_cluster_details: >-
    W3sibmFtZSI6ICJyb29rLWNlcGgtbW9uLWVuZHBvaW50cyIsICJraW5kIjogIkNvbmZpZ01hcCIsICJkYXRhIjogeyJkYXRhIjogIjEwLjE5OC43LjEzNT0xMC4xOTguNy4xMzU6Njc4OSIsICJtYXhNb25JZCI6ICIwIiwgIm1hcHBpbmciOiAie30ifX0sIHsibmFtZSI6ICJyb29rLWNlcGgtbW9uIiwgImtpbmQiOiAiU2VjcmV0IiwgImRhdGEiOiB7ImFkbWluLXNlY3JldCI6ICJhZG1pbi1zZWNyZXQiLCAiZnNpZCI6ICIwMjdlOTc3YS01NGEzLTExZWMtOTliZC0zY2ZkZmViNGNlNGMiLCAibW9uLXNlY3JldCI6ICJtb24tc2VjcmV0In19LCB7Im5hbWUiOiAicm9vay1jZXBoLW9wZXJhdG9yLWNyZWRzIiwgImtpbmQiOiAiU2VjcmV0IiwgImRhdGEiOiB7InVzZXJJRCI6ICJjbGllbnQuaGVhbHRoY2hlY2tlciIsICJ1c2VyS2V5IjogIkFRQSt2S3hod1FoektoQUE3SmpoR3pCbWd6bk41Z0Y2Vjdxb0ZBPT0ifX0sIHsibmFtZSI6ICJyb29rLWNzaS1yYmQtbm9kZSIsICJraW5kIjogIlNlY3JldCIsICJkYXRhIjogeyJ1c2VySUQiOiAiY3NpLXJiZC1ub2RlIiwgInVzZXJLZXkiOiAiQVFBK3ZLeGgxUm54S2hBQW52d1dFNGdtUnhFenVTZU5mVzFFdHc9PSJ9fSwgeyJuYW1lIjogImNlcGgtcmJkIiwgImtpbmQiOiAiU3RvcmFnZUNsYXNzIiwgImRhdGEiOiB7InBvb2wiOiAib2NwLWNlcGgtcmJkIn19LCB7Im5hbWUiOiAibW9uaXRvcmluZy1lbmRwb2ludCIsICJraW5kIjogIkNlcGhDbHVzdGVyIiwgImRhdGEiOiB7Ik1vbml0b3JpbmdFbmRwb2ludCI6ICIxMC4xOTguNy4xMzYiLCAiTW9uaXRvcmluZ1BvcnQiOiAiOTI4MyJ9fSwgeyJuYW1lIjogInJvb2stY3NpLXJiZC1wcm92aXNpb25lciIsICJraW5kIjogIlNlY3JldCIsICJkYXRhIjogeyJ1c2VySUQiOiAiY3NpLXJiZC1wcm92aXNpb25lciIsICJ1c2VyS2V5IjogIkFRQSt2S3hoazBKcUt4QUEzK05sRk1VWHUxajl5Qm1DMitxS3RBPT0ifX1dCg==
type: Opaque
---
apiVersion: ocs.openshift.io/v1
kind: StorageCluster
metadata:
  name: ocs-external-storagecluster
  namespace: openshift-storage
spec:
  arbiter: {}
  encryption:
    kms: {}
  externalStorage:
    enable: true
  labelSelector: {}
  managedResources:
    cephBlockPools: {}
    cephConfig: {}
    cephDashboard: {}
    cephFilesystems: {}
    cephObjectStoreUsers: {}
    cephObjectStores: {}
  version: 4.8.0
