global:
  name: mgmt
  domain: telco.lab
# git repo prefix for target cluster, exaple: cluster-ran1.telco.lab
  cluster_git_prefix: cluster
  namespace: assisted-installer
  base_git_url: https://github.com/sonofspike/cluster-mgmt.telco.lab.git
  operator_catalog_name: redhat-operator-index
#
  values_global_url: https://raw.githubusercontent.com/sonofspike/cluster-mgmt.telco.lab/main
#
  base_ztp_url: https://github.com/sonofspike/cluster-mgmt.telco.lab.git
  # base_ztp_url: https://github.com/sonofspike/clusters-openshift-gitops.git
  values_cluster_prefix_url: https://github.com/sonofspike
  # default_storage_class: "ocs-storagecluster-ceph-rbd"
  default_storage_class: "ocs-external-storagecluster-ceph-rbd"
  dns: 10.198.7.130
  imagesetref_name: "openshift-v4.8.22-mirror"
  pull_secret_name: pull-secret
  pull_secret: '{"auths":{"lab-registry.mgmt.telco.lab":{"auth":"dGVsY29sYWI6UmVkaGF0MDE=","email":"nsatsia@redhat.com"},"lab-registry.mgmt.telco.lab":{"auth":"dGVsY29sYWI6UmVkaGF0MDE=","email":"nsatsia@redhat.com"},"quay.io":{"auth":"dGVsY29sYWI6UmVkaGF0MDE=","email":"nsatsia@redhat.com"},"registry.redhat.io":{"auth":"dGVsY29sYWI6UmVkaGF0MDE=","email":"nsatsia@redhat.com"}}}'
  ssh_key: 'ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBJhdxcSrr+m9htw61kpnzV1SK7DycRv/PhZbGpvVk04nsYeJUfmUGT/VG5jj6zFwNjLH0EXPAv68G34PaV8WSmk= telco.lab'
  ca: |-
    -----BEGIN CERTIFICATE-----
    MIIEhTCCAu2gAwIBAgIBATANBgkqhkiG9w0BAQsFADA0MRIwEAYDVQQKDAlURUxD
    Ty5MQUIxHjAcBgNVBAMMFUNlcnRpZmljYXRlIEF1dGhvcml0eTAeFw0yMTEyMDMw
    MzAwNTFaFw00MTEyMDMwMzAwNTFaMDQxEjAQBgNVBAoMCVRFTENPLkxBQjEeMBwG
    A1UEAwwVQ2VydGlmaWNhdGUgQXV0aG9yaXR5MIIBojANBgkqhkiG9w0BAQEFAAOC
    AY8AMIIBigKCAYEA4D4GCc2uGF4CSTml+hZogYVJTwcMXdIs4An/+KEsEfPmTrqQ
    I+pKbn6CezTc5/to3nd7oCQZbwaOjuc1GmvUkvJmTqBQ3HBTyLaR56Giaa3PvUxU
    jUgmYTcYu0C9E3KPlRBp6O2Gu0IkLF9XJ4QmclItpzw4fIrjs4gqCJYEFLt0qUyi
    4SdYCTajkpnUeC9s7mNdUmvkIljzmQQAlqiEjpRLfbcLWTvykgZWNajgy1D1pQi2
    inkdSzJacAJFlksynyf+L9gQkVLKl12XtVf/ctVv1B5bWCrQ3MFa2TJExc55B3FU
    zxdwleSFvfAPps64+v+sitIcV12tpDBc8hQt5knKsZih7XznKklIOFqVJiQhDeAs
    vVJf/ZR/ydzOBL1KWrty2IAoTENmS/GIu4WIqy/t66MSkEOIfKbtncBmO3BIFYcL
    dcsFNDy2hNj9T/e2q+v8BFopsPd8J1dk9NhMhytYBkwzkx6iLlY45ZdczYGLOw38
    WILsBVcTH0t2MnMtAgMBAAGjgaEwgZ4wHwYDVR0jBBgwFoAUWf4HDI68lgbMqBLM
    N64rAKil+PwwDwYDVR0TAQH/BAUwAwEB/zAOBgNVHQ8BAf8EBAMCAcYwHQYDVR0O
    BBYEFFn+BwyOvJYGzKgSzDeuKwCopfj8MDsGCCsGAQUFBwEBBC8wLTArBggrBgEF
    BQcwAYYfaHR0cDovL2lwYS1jYS50ZWxjby5sYWIvY2Evb2NzcDANBgkqhkiG9w0B
    AQsFAAOCAYEA1xDeWwGiiBF0W9iQimHhmQGtjJTjknim7uGxPLRT6YQYR2t5rRAl
    0NIIQoXrZl2rjgwxRoLgl+w+HIa9yywWJ1focQ/xTIjF3vOBeXCrBh7t06glVMnI
    vGz6DqyLTlwJHSbRIunDaXKMDlP6a3EutzZ+TPJojwXHYdOupm9KNDpsGm0VaksA
    h0QyELkbiyZWd2n+gRqdZUoIHJ5Ha0zdR4FFP+/9OjK9iRFdkkUlq8MCP5jXJouh
    iuHKu0bUlr3OBQpUQGH8iuheuNpEzVVzj/MGUsvUJGRRYNwdamEKjjabcAC72xXp
    aoKAcBLtp+p3mm1GEMProf90jpzV5z4EeoFPPusF+IWSnn/QCZvZMo/bykndh++t
    TS+ITTIc77JjrNWP3RqfeRfUxMz/5m95dKKRSX60hRHCsR/GD+esfk66iivTbYoj
    Pv/TFeyfB2+rOpTtYsgWWZEs4lAg6EnZeTNv2/DiqAONXqPgozfMf2lYW3dAvfrI
    +gulMabIlRlB
    -----END CERTIFICATE-----

gitops:
  namespace: telco-gitops
  common_label: "telco-gitops/ztp: combined-ran"
  service_account: cli-job-sa
  service_account_name: cli-job-sa
  hook_image: registry.redhat.io/openshift4/ose-tools-rhel8@sha256:e44074f21e0cca6464e50cb6ff934747e0bd11162ea01d522433a1a1ae116103
  # hook_image: registry.redhat.io/openshift4/ose-cli:latest

bmh:
  # wget https://releases-art-rhcos.svc.ci.openshift.org/art/storage/releases/rhcos-4.8/48.84.202106301921-0/x86_64/rhcos-48.84.202106301921-0-openstack.x86_64.qcow2.gz?sha256=5a75df7b4d4dc1861093e520187a133eda3439019f280dc6e2f57edf70eb089d
  prov_os_download_url: http://10.198.7.130:8989/rhcos-48.84.202106301921-0-openstack.x86_64.qcow2.gz?sha256=5a75df7b4d4dc1861093e520187a133eda3439019f280dc6e2f57edf70eb089d

lso:
  maxdevice: 10
  minsize: 1Gi

mirror:
  - name: openshift-v4.8.22-mirror
    path: lab-registry.mgmt.telco.lab/telcolab/ocp4822:4.8.22-x86_64

quay:
  config: lab-quay-config-bundle
  operator_source: redhat-operator-index

ai: 
  namespace: "assisted-installer"
  service_config_name: "assisted-service-config"
  registry_url: "lab-registry.mgmt.telco.lab"
  registry_user: "telcolab"
  registry_password: "Redhat01"
  controller_image: "quay.io/edge-infrastructure/assisted-installer-controller@sha256:525e8090f4c12107e6c89b8bae9461098a7d14132d2eebe4c39602348e4293c0"
  os_images:
    osp_version: '4.8'
    rhcos_version: 48.84.202107202156-0
    root_fs_img_url: http://10.198.7.130:8989/rhcos-live-rootfs.x86_64.img
    root_fs_iso_url: http://10.198.7.130:8989/rhcos-4.8.2-x86_64-live.x86_64.iso

nodes:
  masters:
  - name: "m0"
    lso: "true"
    ocs: "true"

  - name: "m1"
    lso: "true"
    ocs: "true"

  - name: "m2"
    lso: "true"
    ocs: "true"
