global:
  name: mgmt
  domain: telco.lab
  namespace: assisted-installer
  base_git_url: https://github.com/sonofspike/cluster-mgmt.telco.lab.git
  operator_catalog_name: redhat-operator-index
#
  values_global_url: https://raw.githubusercontent.com/sonofspike/cluster-mgmt.telco.lab/main
#
  base_ztp_url: https://github.com/sonofspike/openshift-gitops.git
  values_cluster_prefix_url: https://github.com/sonofspike
  api_vip: 10.198.7.139
  ingress_vip: 10.198.7.141
  default_router: 10.198.7.129
  default_storage_class: "ocs-storagecluster-ceph-rbd"
  # default_storage_class: "ocs-external-storagecluster-ceph-rbd"
  dns: 10.198.7.130
  clusternetwork: 10.128.0.0/14
  servicenetwork: 172.30.0.0/16
  imagesetref_name: "openshift-v4.8.19-mirror"
  pull_secret_name: pull-secret
  pull_secret: '{"auths":{"lab-registry.mgmt.telco.lab":{"auth":"bnNhdHNpYTpSZWRoYXQwMQ==","email":"nsatsia@redhat.com"},"lab-registry.mgmt.telco.lab":{"auth":"bnNhdHNpYTpSZWRoYXQwMQ==","email":"nsatsia@redhat.com"},"quay.io":{"auth":"bnNhdHNpYTpSZWRoYXQwMQ==","email":"nsatsia@redhat.com"},"registry.redhat.io":{"auth":"bnNhdHNpYTpSZWRoYXQwMQ==","email":"nsatsia@redhat.com"}}}'
  ssh_key: 'ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBJhdxcSrr+m9htw61kpnzV1SK7DycRv/PhZbGpvVk04nsYeJUfmUGT/VG5jj6zFwNjLH0EXPAv68G34PaV8WSmk= telco.lab'
  ca: |-
    -----BEGIN CERTIFICATE-----
    MIIDlDCCAnygAwIBAgIBATANBgkqhkiG9w0BAQsFADA5MRcwFQYDVQQKDA5MQUIu
    RElLVElPLk5FVDEeMBwGA1UEAwwVQ2VydGlmaWNhdGUgQXV0aG9yaXR5MB4XDTE5
    MDMxMDAzNDM0MloXDTM5MDMxMDAzNDM0MlowOTEXMBUGA1UECgwOTEFCLkRJS1RJ
    Ty5ORVQxHjAcBgNVBAMMFUNlcnRpZmljYXRlIEF1dGhvcml0eTCCASIwDQYJKoZI
    hvcNAQEBBQADggEPADCCAQoCggEBAOEatwt8carWOdYsAoh8BSMg5tUZmU+rUe1L
    fZKN6tA9ytpg4PqWaTRA8eXPfkyzpunf8NXmP1AWSf8LBH5fWUVxzFgmOfyrZroN
    9sLjf+ueuh+LK7tixL56aUkx0fjQecoBpD5rq4JUemjC1QocpHAVZeYkDlvuoXEq
    uhwj1/Dla5JI5YlEeD2AzvNNxjM3s23L+wfvPErKzbbamxFKZQPxCyPCom0Vm7hO
    47WJ6RgVKMlCQGx2zcw8ckS3mj9DJwhHTAcNAdBJyK6AD4PDmk/L7pVYyS6HtCTj
    NKAeedKqLFFGNvTkGCTBMA0aDwn5D1Ti9nqTG9tDm6a8PBmJWk0CAwEAAaOBpjCB
    ozAfBgNVHSMEGDAWgBQK1MC5fwTjULrfW5Z4vY82fnGcNjAPBgNVHRMBAf8EBTAD
    AQH/MA4GA1UdDwEB/wQEAwIBxjAdBgNVHQ4EFgQUCtTAuX8E41C631uWeL2PNn5x
    nDYwQAYIKwYBBQUHAQEENDAyMDAGCCsGAQUFBzABhiRodHRwOi8vaXBhLWNhLmxh
    Yi5kaWt0aW8ubmV0L2NhL29jc3AwDQYJKoZIhvcNAQELBQADggEBAIJ4Hd2BjDK1
    tbeOp0TCmh3V59gaB4RTUQ8eDHKinqzglfWfvg6KsWMAENVRkjBqtEu7YwzMU5jx
    imV/nV7B6euftOLlg3L6uHJyUyqdsb9e8rN2Lt2Zho4e6i726g9FRCVXMNaQVFA4
    6rVNmIrAc88NGffiYxa1ANEfkqbD0RZYggxVBeN5l4C5QVZO/XdQLeUvQaFZir+R
    5ieeL2Zp5BObGec6tWYaAjJwlE5YMQh6IvQQgUfVMGCFrPwdN3KP2jEXW91Dy3rn
    WFBk6T3neXntdKX5ZipQM6qfFbH8DoDdElCvqZkB2bc1AwWaFzYbiEjz0oeowpUw
    tEChGIzF/34=
    -----END CERTIFICATE-----

gitops:
  namespace: telco-gitops
  common_label: "telco-gitops/ztp: combined-ran"
  service_account: cli-job-sa
  service_account_name: cli-job-sa
  hook_image: registry.redhat.io/openshift4/ose-tools-rhel8@sha256:e44074f21e0cca6464e50cb6ff934747e0bd11162ea01d522433a1a1ae116103
  # hook_image: registry.redhat.io/openshift4/ose-cli:latest

bmh:
  prov_os_download_url: http://192.19.130.11:8989/rhcos-48.84.202106301921-0-openstack.x86_64.qcow2.gz?sha256=5a75df7b4d4dc1861093e520187a133eda3439019f280dc6e2f57edf70eb089d

lso:
  maxdevice: 10
  minsize: 1Gi

mirror:
  - name: openshift-v4.8.19-mirror
    path: lab-registry.mgmt.telco.lab/sonofspike/ocp4819:4.8.19-x86_64

quay:
  config: lab-quay-config-bundle
  operator_source: redhat-operator-index

ai: 
  namespace: "assisted-installer"
  service_config_name: "assisted-service-config"
  registry_url: "lab-registry.mgmt.telco.lab"
  registry_user: "nsatsia"
  registry_password: "Redhat01"
  controller_image: "quay.io/edge-infrastructure/assisted-installer-controller@sha256:3f96b21f34cd0c0c605df094190d426dc968d2403cbf5888244df0bfac1d1d0a"
  os_images:
    osp_version: '4.8'
    rhcos_version: 48.84.202107202156-0
    root_fs_img_url: http://hypervisor1.lab.diktio.net:8989/openshift-v4/dependencies/rhcos/4.8/4.8.2/rhcos-live-rootfs.x86_64.img
    root_fs_iso_url: http://hypervisor1.lab.diktio.net:8989/openshift-v4/dependencies/rhcos/4.8/4.8.2/rhcos-4.8.2-x86_64-live.x86_64.iso

nodes:
  masters:
  - name: "m0"
    lso: "true"
    ocs: "true"

  - name: "m1"
    lso: "true"
    ocs: "true"

  - name: "m2"
    lso: "true"
    ocs: "true"
