kind: Secret
apiVersion: v1
metadata:
  name: {{ $.Values.quay.config }}
  namespace: openshift-operators
### nsatsia: need to improve via values.yaml
#
data:
  config.yaml: >- |
    SERVER_HOSTNAME: lab-registry.mgmt.telco.lab
    DISTRIBUTED_STORAGE_CONFIG:
      local_us:
      - RadosGWStorage
      - access_key: QRTMVUVN4X9SCZ6T3RCQ
        bucket_name: mgmt-cluster-bucket
        hostname: 10.198.7.135
        is_secure: false
        port: "80"
        secret_key: WJBO2ai5xRcndqGe3K9QADeDCOIjQt5Vn834iH3G
        storage_path: /datastorage/registry
  ssl.cert: >- |
    -----BEGIN CERTIFICATE-----
    MIIE0TCCAzmgAwIBAgIBDTANBgkqhkiG9w0BAQsFADA0MRIwEAYDVQQKDAlURUxD
    Ty5MQUIxHjAcBgNVBAMMFUNlcnRpZmljYXRlIEF1dGhvcml0eTAeFw0yMTEyMDMx
    MTI5MTVaFw0yMzEyMDQxMTI5MTVaMDoxEjAQBgNVBAoMCVRFTENPLkxBQjEkMCIG
    A1UEAwwbbGFiLXJlZ2lzdHJ5Lm1nbXQudGVsY28ubGFiMIIBIjANBgkqhkiG9w0B
    AQEFAAOCAQ8AMIIBCgKCAQEAlO1eKNA4hYGxuNIbRX8ji5hZ/q2MgLRbT2YK0YjA
    0G6ATkCQXzIUEot3lbJkFulwJ3FU9+X19Mp3r7JmubZz9sZjXxOTxLAH3oYHBA2A
    OFZdIk6CsPtqNzKcUxD+6DEE4DDD7Qa0OhdAOIaRcwVbdpXx9uV4kus+/Yw8MrF5
    gu1yY7EVZTK7OrgFxwld3anROwzRkp8pPGel2UltJhcJADXbOSdSjmG4/prT2GCx
    ay7eI/oi2iaYrmYz0KznOOAyKpStXM+3uDsrbvzai28dBk1fIaLqCjLXQQRCW0Rc
    JAZ7emnImyQIgxrvJKETDWwcK9mDmrPjdM29H8vLvVEMzwIDAQABo4IBZjCCAWIw
    HwYDVR0jBBgwFoAUWf4HDI68lgbMqBLMN64rAKil+PwwOwYIKwYBBQUHAQEELzAt
    MCsGCCsGAQUFBzABhh9odHRwOi8vaXBhLWNhLnRlbGNvLmxhYi9jYS9vY3NwMA4G
    A1UdDwEB/wQEAwIE8DAdBgNVHSUEFjAUBggrBgEFBQcDAQYIKwYBBQUHAwIwdAYD
    VR0fBG0wazBpoDGgL4YtaHR0cDovL2lwYS1jYS50ZWxjby5sYWIvaXBhL2NybC9N
    YXN0ZXJDUkwuYmluojSkMjAwMQ4wDAYDVQQKDAVpcGFjYTEeMBwGA1UEAwwVQ2Vy
    dGlmaWNhdGUgQXV0aG9yaXR5MB0GA1UdDgQWBBRjjki6Pbt+WtfMgsWtTEoyFNkf
    7DA+BgNVHREENzA1ghtsYWItcmVnaXN0cnkubWdtdC50ZWxjby5sYWKCFmluZ3Jl
    c3MubWdtdC50ZWxjby5sYWIwDQYJKoZIhvcNAQELBQADggGBANEKK6vORNKSIWuV
    C7BA/v7MbLEgSIxMvMTNN7T9JbOIpO/MBFHYVx9C+fg/EPmpk/yfWEvR/lnKBy10
    GbJkj2Po+wNw3+na+7Roxt3RU9xNy2UvDZmcufvmhQqWcHAK27X1u7lxIRbh96U8
    xVnI75KYelyAeGWR/Vq/5ugN+n1DBIRZ/btbq6H9rDr0AHueT1TXIjWGCH9+5GP5
    j/mLpf3xR7PRDk0LA/DzeMytnZ2oD7xI2VoaUISivdevGAV6ehCyjBeZMsC+Y6Uc
    G3hLskmpjvR05G5n3T/AXQae5kdMctasJq8tYNu6UytqD7jHt11rFubC1CZ5FGxJ
    tqCkd+O7vIXAThAoR/rZ57J7LRHV4AJFJSNZ4fYicdZktKjoC0NYUwcFgPfWUD0K
    Fd4GZwqQih5TzjBJscnerJM7es73kEWI3fGxGVWI/vsPkgVKsK9o5cbtn97H/Ku7
    v8+j8vWbooAkrHZ2wD/jolDjeUAkc+8yCrxb5+AiFIibLg8rIQ==
    -----END CERTIFICATE-----
  ssl.key: >- |
    -----BEGIN PRIVATE KEY-----
    MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCU7V4o0DiFgbG4
    0htFfyOLmFn+rYyAtFtPZgrRiMDQboBOQJBfMhQSi3eVsmQW6XAncVT35fX0ynev
    sma5tnP2xmNfE5PEsAfehgcEDYA4Vl0iToKw+2o3MpxTEP7oMQTgMMPtBrQ6F0A4
    hpFzBVt2lfH25XiS6z79jDwysXmC7XJjsRVlMrs6uAXHCV3dqdE7DNGSnyk8Z6XZ
    SW0mFwkANds5J1KOYbj+mtPYYLFrLt4j+iLaJpiuZjPQrOc44DIqlK1cz7e4Oytu
    /NqLbx0GTV8houoKMtdBBEJbRFwkBnt6acibJAiDGu8koRMNbBwr2YOas+N0zb0f
    y8u9UQzPAgMBAAECggEAT3Y3f19aSSHiSdMRagtkU99+ZT0EcsfI0JyJuTNWbeAH
    5bjdT23Q9/QiYmVEslTr2p/Fzl+M1IgTRFPUK9MGHO3Np7UyawfhqwGoTKlHeMfb
    +aoaYYREMB94+XlgCVPeXiCm6ZliIHy3b3Gdudlp6+Qlrq7RntKWUYK5u/Kl+w0W
    UirUpMUDL0AqNyzC+Za6FA3h/Gb6fe1qE0FkBJITqcNH3PXO9KoyPSs3Y4gcLZLH
    dA3hRZcyVSpaaM3OmRU/7EbBfzM5ZPsSxCv1eIOsgO1R/3PkQowxM+Y8TnLP+TH/
    4EWykcBQltWuUzRBOTZxzn8z0YvLQU1gVLO+E5lpwQKBgQDFmlgRNSRSStwDruKw
    br3aJXoRRT6zvPEO9KbmbHwcYCS8lUfYdbwC79UO3xX5b3xUBODFlEZwNQhScJkP
    aR6xXEb0EPHzXj1amrZXdVPqvWgt3aYcs4sHYrERD2o7bWrIAxH7Ad44FbPKSw+L
    MxHe5otq/VZAw965MlZZPjaAEwKBgQDA8HZtFexD5BAQcsNUqBJM3aQpATtGyI58
    LmerwTuh+1LDJ8jmT8BPGaBPq+1sGKM3bqdaM7dWPgDRtu6ZJu9puA64m8bc1NWF
    3i7HsfJlf3eXMn29xVhs1F9fh9T8QTlMmrxX4aQ1WJC/dmTtmpMWK3ghgvRanYsH
    MTEjBlcv1QKBgAsEbgCXm+zSq62w5Ia9xewRxtqLp9FRqYcR8PRL/CeA3Mt+70CM
    X+0x/gkUOx9rLd1pYDbj64F6E3q1OHN5gvKUmIgnIbZV/Mm+cogxzHn8EYDtKMPU
    5t2EjSbMWznxAdEhCrGaCw/JdfrDcJxsPoTVCdTvRw3ZXeOpgNL8+wDtAoGAHrPl
    VJShhWg8ejGZDda1GtBGeFP+19PAgNhtnPJiB/PThsTE/omAY9YDIcqNPJ9rEb4l
    GYCTU0EIplbC/1In1R36EbyQV8HyvJvPu+2AUlCHemMJiXJnEOJ2zt/xr7a9ZIhX
    InEAzZBrcFxp0TnA4E1Ij6SkN+tMHXfhht5Sb4UCgYEAqngmM54DTCUJ2ZdZOud0
    oxRKZ1/dUPPN3m/TzBxSxrt34rghjKT3T3iBRsbKfqhWCeTZCE/NhS2ekwE6eVcN
    4isJNLJj+ZFWSv1lgUZA0OHhiXg0JLyXzeou7jFtG2ENKXBlI3iOFadjejCBYhyA
    efyEvw48SF5bxNJ8r9QDPiQ=
    -----END PRIVATE KEY-----
type: Opaque
