---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: 'ztp-deploy-{{ $.Values.cluster.name }}.{{ $.Values.global.domain }}'
  namespace: {{ $.Values.gitops.namespace }}
spec:
  destination:
    namespace: {{ $.Values.gitops.namespace }}
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    repoURL: '{{ $.Values.global.values_cluster_prefix_url }}/{{ $.Values.global.cluster_git_prefix }}-{{ $.Values.cluster.name }}.{{ $.Values.global.domain }}.git'
    path: ztp/deploy
    targetRevision: HEAD
    helm:
      valueFiles:
      - "{{ $.Values.global.values_global_url }}/values.yaml"
      - "{{ $.Values.global.values_cluster_prefix_url }}/{{ $.Values.global.cluster_git_prefix }}-{{ $.Values.cluster.name }}.{{ $.Values.global.domain }}/raw/main/values.yaml"
