apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: redhat-operator-index
  namespace: openshift-marketplace
spec:
  image: lab-registry.mgmt.telco.lab/telcolab/telcolab-redhat-operator-index:v4.8
  sourceType: grpc
