---
###############################################################################
# SR-IOV Network Definition for the NS of the workload
# vran-mgmt-cu + vlan 604 + oran_mh_netdevice
###############################################################################
# NS = cnf-cu
apiVersion: sriovnetwork.openshift.io/v1
kind: SriovNetwork
metadata:
  name: vran-mgmt-cu
  namespace: openshift-sriov-network-operator
spec:
  resourceName: oran_mh_netdevice_cu
  # Namespace with the CU workload
  networkNamespace: cnf-cu
  vlan: 604
  ipam: |-
    {"type": "static"}
  linkState: auto
  # spoofChk: "<spoof_check>"
  # maxTxRate: <max_tx_rate>
  # minTxRate: <min_rx_rate>
  vlanQoS: 2
  # trust: "<trust_vf>"
  # capabilities: <capabilities>
