---
###############################################################################
# SR-IOV Network Definition for the NS of the workload
# oran-bh-s1c + vlan 602 + vran_bh_vfio
###############################################################################
# NS = cnf-cu
apiVersion: sriovnetwork.openshift.io/v1
kind: SriovNetwork
metadata:
  name: oran-bh-s1c
  namespace: openshift-sriov-network-operator
spec:
  resourceName: oran_bh_vfio
  # Namespace with the CU workload
  networkNamespace: cnf-cu
  vlan: 602
  ipam: |-
    {}
  linkState: auto
  # spoofChk: "<spoof_check>"
  # maxTxRate: <max_tx_rate>
  # minTxRate: <min_rx_rate>
  vlanQoS: 7
  # trust: "<trust_vf>"
  # capabilities: <capabilities>