apiVersion: v1
kind: Secret
metadata:
  name: bmc-{{ $.Values.cluster.name }}-{{ $.Values.node.site }}-{{ $.Values.node.name }}
  namespace: {{ $.Values.global.namespace }}
data:
  username: {{ $.Values.node.bmc_username | b64enc }}
  password: {{ $.Values.node.bmc_password | b64enc }}
type: Opaque
---
