# Need ceph-external-cluster-details-exporter.py from your stable OCS operator
# to genrate the external_cluster_details
---
kind: Secret
apiVersion: v1
metadata:
  name: rook-ceph-external-cluster-details
  namespace: openshift-storage
data:
  external_cluster_details: >-
    W3tuYW1lOiByb29rLWNlcGgtbW9uLWVuZHBvaW50cywga2luZDogQ29uZmlnTWFwLCBkYXRhOiB7ZGF0YTogMTAuMTk4LjcuMTM1PTEwLjE5OC43LjEzNTo2Nzg5LCBtYXhNb25JZDogMCwgbWFwcGluZzoge319fSwge25hbWU6IHJvb2stY2VwaC1tb24sIGtpbmQ6IFNlY3JldCwgZGF0YToge2FkbWluLXNlY3JldDogYWRtaW4tc2VjcmV0LCBmc2lkOiAwMjdlOTc3YS01NGEzLTExZWMtOTliZC0zY2ZkZmViNGNlNGMsIG1vbi1zZWNyZXQ6IG1vbi1zZWNyZXR9fSwge25hbWU6IHJvb2stY2VwaC1vcGVyYXRvci1jcmVkcywga2luZDogU2VjcmV0LCBkYXRhOiB7dXNlcklEOiBjbGllbnQuaGVhbHRoY2hlY2tlciwgdXNlcktleTogQVFBK3ZLeGh3UWh6S2hBQTdKamhHekJtZ3puTjVnRjZWN3FvRkE9PX19LCB7bmFtZTogcm9vay1jc2ktcmJkLW5vZGUsIGtpbmQ6IFNlY3JldCwgZGF0YToge3VzZXJJRDogY3NpLXJiZC1ub2RlLCB1c2VyS2V5OiBBUUErdkt4aDFSbnhLaEFBbnZ3V0U0Z21SeEV6dVNlTmZXMUV0dz09fX0sIHtuYW1lOiBjZXBoLXJiZCwga2luZDogU3RvcmFnZUNsYXNzLCBkYXRhOiB7cG9vbDogb2NwLWNlcGgtcmJkfX0sIHtuYW1lOiBtb25pdG9yaW5nLWVuZHBvaW50LCBraW5kOiBDZXBoQ2x1c3RlciwgZGF0YToge01vbml0b3JpbmdFbmRwb2ludDogMTAuMTk4LjcuMTM2LCBNb25pdG9yaW5nUG9ydDogOTI4M319LCB7bmFtZTogcm9vay1jc2ktcmJkLXByb3Zpc2lvbmVyLCBraW5kOiBTZWNyZXQsIGRhdGE6IHt1c2VySUQ6IGNzaS1yYmQtcHJvdmlzaW9uZXIsIHVzZXJLZXk6IEFRQSt2S3hoazBKcUt4QUEzK05sRk1VWHUxajl5Qm1DMitxS3RBPT19fV0K
type: Opaque
---
apiVersion: ocs.openshift.io/v1
kind: StorageCluster
metadata:
  name: ocs-external-storagecluster
  namespace: openshift-storage
spec:
  arbiter: {}
  encryption:
    kms: {}
  externalStorage:
    enable: true
  labelSelector: {}
  managedResources:
    cephBlockPools: {}
    cephConfig: {}
    cephDashboard: {}
    cephFilesystems: {}
    cephObjectStoreUsers: {}
    cephObjectStores: {}
  version: 4.8.5
