---
###############################################################################
# SR-IOV Network Definition for workload (e.g. CNF DU with m-plane)
# oran-fh-netdevice + vlan 701 + oran-fh-netdevice
###############################################################################
# NS = cnf-du
apiVersion: sriovnetwork.openshift.io/v1
kind: SriovNetwork
metadata:
  name: oran-fh-netdevice
  namespace: openshift-sriov-network-operator
spec:
  resourceName: oran_fh_netdevice
  # Namespace with the DU workload
  networkNamespace: cnf-du
  vlan: 701
  ipam: |-
    {"type": "static"}
  linkState: auto
  # spoofChk: "<spoof_check>"
  # maxTxRate: <max_tx_rate>
  # minTxRate: <min_rx_rate>
  vlanQoS: 2
  # trust: "<trust_vf>"
  # capabilities: <capabilities>
