---
###############################################################################
# SR-IOV Network Definition for the NS of the workload
# vran-mgmt-du + vlan 604 + oran_mh_netdevice
###############################################################################
# NS = cnf-du
apiVersion: sriovnetwork.openshift.io/v1
kind: SriovNetwork
metadata:
  name: vran-mgmt-du
  namespace: openshift-sriov-network-operator
spec:
  # resourceName: oran_mh_netdevice_du
  resourceName: oran_fh_netdevice
  # Namespace with the DU workload
  networkNamespace: cnf-du
  vlan: 604
  ipam: |-
    {"type": "static"}
  linkState: auto
  # spoofChk: "<spoof_check>"
  # maxTxRate: <max_tx_rate>
  # minTxRate: <min_rx_rate>
  vlanQoS: 2
  # trust: "<trust_vf>"
  # capabilities: <capabilities>
