---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- 00-ran-du-mcp.yaml
- 01a-oran-fh-sriov-node-network-policy.yaml
- 01b-oran-fh-sriov-cu-plane.yaml
- 01b-oran-fh-sriov-m-plane.yaml
# - 02a-oran-mh-sriov-node-network-policy.yaml
- 02b-oran-mh-netdevice-du.yaml
- 02c-vran-mgmt-netdevice-du.yaml
- 50-ran-du-disable-chronyd.yaml